pub mod allocation_trace;
pub mod app;
pub mod backend;
pub mod canvas;
pub mod cell_text;
pub mod command_blocks;
pub mod config;
pub mod containers;
pub mod cursor_preview;
pub mod diagnostics;
pub mod frame_timing;
pub mod ghostty_snapshot;
pub mod host;
pub mod input;
pub mod input_selection;
pub mod interaction;
pub mod logging;
pub mod mouse;
pub mod perf_trace;
pub mod process_metrics;
pub mod render;
pub mod selection;
pub mod shell;
pub mod smooth_scroll;
pub mod snapshot;
pub mod terminal_font;
pub mod terminal_grid;
pub mod text_width;
pub mod trace_sink;
pub mod workspace;
pub mod workspace_render;

#[global_allocator]
static GLOBAL_ALLOCATOR: allocation_trace::CountingAllocator = allocation_trace::CountingAllocator;
